name: Deploy FoodExpress Application to Minikube on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Connect to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "===== Updating Project Repository ====="
            cd ~/Task7-foodexpress-K8s
            git pull origin main

            echo "===== Starting Minikube Cluster ====="
            minikube status || minikube start --driver=docker

            echo "===== Enabling Required Minikube Add-ons ====="
            minikube addons enable ingress
            minikube addons enable metrics-server
            minikube addons enable storage-provisioner
            minikube addons enable default-storageclass

            echo "===== Pulling Latest Docker Images ====="
            docker pull madhu934652/food-express-backend:latest
            docker pull madhu934652/food-express-frontend:latest

            echo "===== Deploying Kubernetes Resources ====="
            kubectl apply -f kubernetes/

            echo "===== Restarting Application Deployments ====="
            kubectl rollout restart deployment/backend -n foodexpress
            kubectl rollout restart deployment/frontend -n foodexpress

            echo "===== Waiting for Deployments to Complete ====="
            kubectl rollout status deployment/mysql -n foodexpress
            kubectl rollout status deployment/backend -n foodexpress
            kubectl rollout status deployment/frontend -n foodexpress

            echo "===== Deployment Summary ====="

            echo ""
            echo "Pods"
            kubectl get pods -n foodexpress

            echo ""
            echo "Services"
            kubectl get svc -n foodexpress

            echo ""
            echo "Persistent Volume Claims"
            kubectl get pvc -n foodexpress

            echo ""
            echo "Persistent Volumes"
            kubectl get pv

            echo ""
            echo "Horizontal Pod Autoscaler"
            kubectl get hpa -n foodexpress

            echo ""
            echo "Ingress"
            kubectl get ingress -n foodexpress

            echo ""
            echo "✅ FoodExpress deployment completed successfully."
